// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `file.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.lpmas.file.component;

public final class FileServiceHolder extends Ice.ObjectHolderBase<FileService>
{
    public
    FileServiceHolder()
    {
    }

    public
    FileServiceHolder(FileService value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof FileService)
        {
            value = (FileService)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _FileServiceDisp.ice_staticId();
    }
}
