// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `file.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.lpmas.file.component;

public interface FileService extends Ice.Object,
                                       _FileServiceOperations, _FileServiceOperationsNC
{
    public static final String ice_staticId = "::com::lpmas::file::component::FileService";

    public static final long serialVersionUID = -1844426163L;
}
